spring:
  datasource:
    url: jdbc:sqlserver://hbcdvb101.harambee.co.za;databaseName=Team2_db;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: teamproj
    password: Secret123$

  jpa:
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
      format_sql: true