spring:
    jpa:
        show-sql: true
        properties:
        hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true

  datasource:
      url: jdbc:sqlserver://hbcdvb101.harambee.co.za;databaseName=team2_db; encrypt=true;trustServerCertificate=true
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: teamproj
      password: Secret123$
